import {ISize} from './types';

export const CommonSizes = {
  font: {
    extraSmall: 11,
    extraSmallPlus: 12,
    small: 14,
    smallPlus: 15,
    medium: 16,
    mediumPlus: 18,
    extraMedium: 20,
    large: 22,
    largePlus: 28,
    extraLarge: 34,
    extraLargePlus: 44,
  } as Readonly<ISize['font']>,
  letterSpacing: {
    extraSmall: 0.07,
    extraSmallPlus: 0,
    small: -0.08,
    smallPlus: -0.24,
    medium: -0.41,
    mediumPlus: 0.38,
    large: 0.35,
    largePlus: 0.36,
    extraLarge: 0.37,
    extraLargePlus: 0.37,
  } as Readonly<ISize['letterSpacing']>,
  lineHeight: {
    extraSmall: 13,
    extraSmallPlus: 16,
    small: 19,
    smallPlus: 20,
    medium: 22,
    mediumPlus: 25,
    large: 28,
    largePlus: 34,
    extraLarge: 41,
    extraLargePlus: 52,
  } as Readonly<ISize['lineHeight']>,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  } as Readonly<ISize['spacing']>,
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  } as Readonly<ISize['borderRadius']>,
  borderWidth: {
    small: 1,
    medium: 2,
    large: 3,
  } as Readonly<ISize['borderWidth']>,
};
